apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keyvaultsample
    aadpodidbinding: keyvaultsampleidentity
  name: keyvaultsample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keyvaultsample
  template:
    metadata:
      labels:
        app: keyvaultsample
        aadpodidbinding: keyvaultsampleidentity
      name: keyvaultsample
    spec:
      containers:
      - name: keyvaultsample
        image: rucheeg/keyvault-aad-pod-identity:1.1
        env:
        - name: AZURE_KEYVAULT_NAME
          value: ap121998-pi-keyvault
        - name: AZURE_KEYVAULT_SECRET_NAME
          value: TestSecret
        - name: AZURE_KEYVAULT_SECRET_VERSION
          value: 46c28fbcc266430ea1fc74b9a7cf1d38
---
apiVersion: v1
kind: Service
metadata:
  name: keyvaultsample
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: keyvaultsample
  type: LoadBalancer