apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nodetodosample
    aadpodidbinding: keyvaultsampleidentity
  name: nodetodosample
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodetodosample
  template:
    metadata:
      labels:
        app: nodetodosample
        aadpodidbinding: keyvaultsampleidentity
      name: nodetodosample
    spec:
      containers:
      - name: nodetodosample
        image: rucheeg/node-todo:1.1 
---
apiVersion: v1
kind: Service
metadata:
  name: nodetodosample
  namespace: default
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: nodetodosample
  type: LoadBalancer