 

// This file was automatically generated by the PetaPoco T4 Template
// Do not make changes directly to this file - edit the template instead
// 
// The following connection settings were used to generate this file
// 
//     Connection String Name: `DCS`
//     Provider:               `System.Data.SqlClient`
//     Connection String:      `Data Source=LAPHOME3\SQLEXPRESS;Initial Catalog=test;Trusted_Connection=Yes`
//     Schema:                 ``
//     Include Views:          `False`

//     Factory Name:          `SqlClientFactory`
 