// <auto-generated />
// This file was generated by a T4 template.
// Don't change it directly as your change would get overwritten.  Instead, make changes
// to the .tt file (i.e. the T4 template) and save it to regenerate this file.

// Make sure the compiler doesn't complain about missing Xml comments
#pragma warning disable 1591

using System;

using ServiceStack.DataAnnotations;
using ServiceStack.Model;
using ServiceStack;

namespace DCSSample
{
	[Alias("SourceDeviceType")]
    public partial class SourceDeviceType : IHasId<int> 
    {
		public SourceDeviceType()
		{
		}

        [Alias("Id")]
        [AutoIncrement]
        public int Id { get; set; }
        [Required]
        public int ClientId { get; set; }
                 [Compute]        
         [Required]
        public string Display { get; set; }
        [Required]
        public string Name { get; set; }
        public string Description { get; set; }
        [Required]
        public DateTime CreatedOn { get; set; }
        [Required]
        public string CreatedBy { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    }

}
#pragma warning restore 1591
